# Have a file called config.yml override these values

# oauth token for the github account being used. needs scoped for hooks and stuff.
oauth_token:

# locate the repository by owner and name. for example Felk/pokeset-ci or TwitchPlaysPokemon/pokecat
repository:

# base path for the webhook, for example https://example.com
webhook_basepath:

# port of the webserver that will be running to receive webhook calls
http_port: 8080
